runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: previous.app
- url: /register
  script: previous.app
- url: /login
  script: previous.app
- url: /previous
  script: previous.app

libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: m2m-ehealth:europe-west1:ehealth-db
    CLOUDSQL_USER: ehealth
    CLOUDSQL_PASSWORD: ehealthCttC
# [END env_variables]